from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, List, Optional

import requests
from flask import current_app


DEFAULT_API_URL = "https://api.spacelift.io/graphql"
DEFAULT_TIMEOUT = float(os.getenv("SPACELIFT_HTTP_TIMEOUT", "20"))


def _load_spacelift_token(env: Optional[Dict[str, str]] = None) -> str:
    env = env or os.environ
    token = env.get("SPACELIFT_API_KEY") or env.get("SPACELIFT_TOKEN")
    if token:
        current_app.logger.info("Spacelift: using token from env (present=%s)", bool(token.strip()))
        return token.strip()

    env_key_id = env.get("SPACELIFT_API_KEY_ID")
    env_key_secret = env.get("SPACELIFT_API_KEY_SECRET")
    if env_key_id and env_key_secret:
        current_app.logger.info("Spacelift: exchanging api_key_id/api_key_secret from env for JWT")
        return _exchange_api_key_for_jwt(env_key_id.strip(), env_key_secret.strip())

    config_path = env.get("SPACELIFT_CONFIG")
    if not config_path:
        raise RuntimeError("SPACELIFT_API_KEY or SPACELIFT_CONFIG must be set")

    if not os.path.exists(config_path):
        raise RuntimeError(f"SPACELIFT_CONFIG not found: {config_path}")

    text = open(config_path, "r", encoding="utf-8").read()
    key_id_match = re.search(r'^\s*api_key_id\s*=\s*([^\s#]+)\s*$', text, re.MULTILINE)
    key_secret_match = re.search(r'^\s*api_key_secret\s*=\s*([^\s#]+)\s*$', text, re.MULTILINE)
    if key_id_match and key_secret_match:
        current_app.logger.info("Spacelift: exchanging api_key_id/api_key_secret for JWT")
        return _exchange_api_key_for_jwt(key_id_match.group(1), key_secret_match.group(1))

    # Config files generated by the Spacelift CLI can contain both a reusable
    # key pair and a cached JWT. Prefer the key pair so an expired or stale JWT
    # cannot shadow newly issued credentials.
    match = re.search(r'^\s*token\s*=\s*"([^"]+)"\s*$', text, re.MULTILINE)
    if match:
        current_app.logger.info("Spacelift: using token from config")
        return match.group(1)

    raise RuntimeError("SPACELIFT_CONFIG does not contain a usable token")


def _api_url() -> str:
    url = os.getenv("SPACELIFT_API_URL") or current_app.config.get("SPACELIFT_API_URL")
    resolved = (url or DEFAULT_API_URL).strip()
    current_app.logger.info("Spacelift: API URL=%s", resolved)
    return resolved


def _account_name() -> str:
    acct = (
        os.getenv("SPACELIFT_ACCOUNT_NAME")
        or os.getenv("SPACELIFT_ORG")
        or current_app.config.get("SPACELIFT_ACCOUNT_NAME")
        or current_app.config.get("SPACELIFT_ORG")
    )
    acct = (acct or "").strip()
    if not acct:
        raise RuntimeError("SPACELIFT_ACCOUNT_NAME must be set")
    current_app.logger.info("Spacelift: account=%s", acct)
    return acct


def _graphql_request(query: str, variables: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    token = _load_spacelift_token()
    url = _api_url()
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "Spacelift-Account-Name": _account_name(),
    }
    payload = {"query": query, "variables": variables or {}}
    resp = requests.post(url, headers=headers, data=json.dumps(payload), timeout=DEFAULT_TIMEOUT)
    current_app.logger.info("Spacelift: GraphQL status=%s", resp.status_code)
    if resp.status_code >= 400:
        raise RuntimeError(f"Spacelift API error {resp.status_code}: {resp.text}")
    data = resp.json()
    if data.get("errors"):
        raise RuntimeError(f"Spacelift API errors: {data['errors']}")
    return data.get("data") or {}


def _exchange_api_key_for_jwt(api_key_id: str, api_key_secret: str) -> str:
    query = """
    mutation GetSpaceliftToken($id: ID!, $secret: String!) {
      apiKeyUser(id: $id, secret: $secret) {
        jwt
      }
    }
    """
    url = _api_url()
    headers = {
        "Content-Type": "application/json",
        "Spacelift-Account-Name": _account_name(),
    }
    payload = {"query": query, "variables": {"id": api_key_id, "secret": api_key_secret}}
    resp = requests.post(url, headers=headers, data=json.dumps(payload), timeout=DEFAULT_TIMEOUT)
    current_app.logger.info("Spacelift: token exchange status=%s", resp.status_code)
    if resp.status_code >= 400:
        raise RuntimeError(f"Spacelift token exchange error {resp.status_code}: {resp.text}")
    data = resp.json()
    if data.get("errors"):
        raise RuntimeError(f"Spacelift token exchange errors: {data['errors']}")
    jwt = (data.get("data") or {}).get("apiKeyUser", {}).get("jwt")
    if not jwt:
        raise RuntimeError("Spacelift token exchange returned no jwt")
    return jwt


def list_spaces() -> List[Dict[str, Any]]:
    query = """
    query GetSpaces {
      spaces {
        id
        name
        description
        parentSpace
        inheritEntities
        accessLevel
        labels
      }
      allowNonRootAdminSpaceCreation
    }
    """
    data = _graphql_request(query)
    return data.get("spaces") or []


def list_aws_integrations() -> List[Dict[str, Any]]:
    query = """
    query SearchAWSIntegrations {
      awsIntegrations(includeLegacy: false) {
        id
        name
        roleArn
        durationSeconds
        generateCredentialsInWorker
        autoattachEnabled
        externalId
        region
        labels
        spaceDetails {
          id
          name
          accessLevel
        }
        hasAttachedStacks
      }
    }
    """
    data = _graphql_request(query)
    return data.get("awsIntegrations") or []


def get_status_counts() -> Dict[str, int]:
    """
    Return compact counts used by status pages in a single GraphQL call.

    This is intentionally lightweight and avoids making multiple API requests
    when only summary numbers are needed.
    """
    query = """
    query StatusCounts {
      awsIntegrations(includeLegacy: false) {
        id
      }
      spaces {
        id
      }
    }
    """
    data = _graphql_request(query)
    aws = data.get("awsIntegrations") or []
    spaces = data.get("spaces") or []
    return {
        "aws_integrations": len(aws),
        "spaces": len(spaces),
    }
