"""GitHub transport using Praxis's existing GitHub App authentication."""
import base64
import io
import json
import os
import zipfile
from urllib.parse import quote

import requests
from services.github_helpers import github_api
from . import store


def repository():
    repo = os.getenv('PRAXIS_ENVIRONMENTS_REPOSITORY', 'siggikrol/praxis-environments')
    if not store.REPO.fullmatch(repo):
        raise ValueError('Invalid environments repository configuration.')
    return repo


def connected():
    return all(os.getenv(k) for k in ('GITHUB_APP_ID', 'GITHUB_INSTALLATION_ID', 'GITHUB_PRIVATE_KEY'))


def request(method, path, **kwargs):
    if not connected() and method != 'GET':
        raise ValueError('Connect the GitHub App before using Git actions. Local configuration and downloads remain available.')
    try:
        if connected():
            response = github_api._request(method, path, **kwargs)
        else:
            response = requests.get('https://api.github.com' + path, timeout=30, headers={'Accept': 'application/vnd.github+json'}, **kwargs)
        github_api._raise_for_status(response)
        return response.json() if response.content else {}
    except (RuntimeError, requests.RequestException) as exc:
        # Do not reflect raw API bodies or credentials into flash messages.
        raise ValueError('GitHub request failed. Check App permissions, repository access and workflow setup.') from exc


def repo_path(repo):
    if not store.REPO.fullmatch(repo):
        raise ValueError('Invalid repository.')
    return '/repos/' + repo


def head(repo):
    root = repo_path(repo)
    info = request('GET', root)
    branch = info['default_branch']
    return branch, request('GET', root + '/commits/' + quote(branch, safe=''))['sha']


def versions(repo):
    # Resolve tags to commits (including annotated tags); never use a mutable tag at execution time.
    root = repo_path(repo)
    result = []
    for page in range(1, 11):
        tags = request('GET', root + '/tags', params={'per_page': 100, 'page': page})
        result.extend({'tag': t['name'], 'commit': t['commit']['sha']} for t in tags)
        if len(tags) < 100:
            break
    return result


def contents(repo, path, ref):
    value = request('GET', repo_path(repo) + '/contents/' + quote(path, safe='/'), params={'ref': ref})
    if value.get('encoding') != 'base64':
        raise ValueError('Git file could not be read.')
    return base64.b64decode(value['content']).decode()


def pull_request(repo, branch, files, title):
    root = repo_path(repo)
    base, sha = head(repo)
    commit = request('GET', root + '/git/commits/' + sha)
    tree = request('POST', root + '/git/trees', json={'base_tree': commit['tree']['sha'], 'tree': [
        {'path': path, 'mode': '100644', 'type': 'blob', 'content': content} for path, content in files.items()]})
    new = request('POST', root + '/git/commits', json={'message': title, 'tree': tree['sha'], 'parents': [sha]})
    request('POST', root + '/git/refs', json={'ref': 'refs/heads/' + branch, 'sha': new['sha']})
    return request('POST', root + '/pulls', json={'title': title, 'head': branch, 'base': base,
        'body': 'Generated by Praxis. Review the configuration and required checks before merging.'})


def dispatch(repo, branch, inputs):
    request('POST', repo_path(repo) + '/actions/workflows/praxis-stack.yml/dispatches',
            json={'ref': branch, 'inputs': inputs})


def workflow_runs(repo, commit=None):
    params = {'per_page': 100}
    if commit:
        params['head_sha'] = commit
    return request('GET', repo_path(repo) + '/actions/runs', params=params).get('workflow_runs', [])


def report(repo, run_id):
    root = repo_path(repo)
    artifacts = request('GET', root + f'/actions/runs/{int(run_id)}/artifacts')['artifacts']
    artifact = next((a for a in artifacts if a['name'] == 'praxis-result' and not a['expired']), None)
    if not artifact:
        raise ValueError('The workflow has no available Praxis result artifact.')
    # Redirect is a signed GitHub blob URL. Never forward the App Authorization header to it.
    response = github_api._request('GET', root + f"/actions/artifacts/{artifact['id']}/zip", allow_redirects=False)
    if response.status_code != 302:
        raise ValueError('Could not download the workflow result.')
    with requests.get(response.headers['Location'], timeout=30, stream=True) as download:
        download.raise_for_status()
        chunks, size = [], 0
        for chunk in download.iter_content(65536):
            size += len(chunk)
            if size > 2_000_000:
                raise ValueError('Workflow result exceeds 2 MB.')
            chunks.append(chunk)
    with zipfile.ZipFile(io.BytesIO(b''.join(chunks))) as archive:
        info = archive.getinfo('result.json')
        if info.file_size > 1_000_000:
            raise ValueError('Workflow result is too large.')
        return json.loads(archive.read(info))
