# --- Rancher Helm Pipelines (defaults for multi-vpc) ---
RANCHER_HELM_PIPELINES_DEFAULTS = {
    "helm_iac_cds": [
        "helm-app-db-resource-deployment/ilp",
        "helm-app-db-resource-deployment/cgs",
        "helm-app-db-resource-deployment/pmv",
        "helm-init-global-envs/ilp",
        "helm-init-global-envs/cgs",
        "helm-init-global-envs/pmv",
        "helm-checksum-report/ilp",
        "helm-checksum-report/cgs",
        "helm-checksum-report/pmv",
        "helm-external-dns-records/ilp",
        "helm-external-dns-records/cgs",
        "helm-external-dns-records/pmv",
        "helm-fim-checksum-report",
        "helm-cert-manager",
        "helm-elasticsearch",
        "helm-finops",
        "helm-fluent-bit",
        "helm-istio",
        "helm-monitoring",
        "helm-rmq",
        "helm-support-charts",
        "helm-external-secrets",
        "helm-vault-agent-injector",
        "helm-vault-essentials",
        "helm-vault-secrets-bootstrap",
        "helm-vault-server",
    ],
    "helm_app_cds": [
        "application-cw",
        "application-ilp",
        "application-rgs",
        "application-rng",
        "application-idp",
        "application-cgs",
        "application-cr",
        "application-pmv",
        "application-ilp-pdf",
        "application-cgs-pdf",
        "application-pmv-pdf",
    ],
    "helm_bootstrap_cds": [
        "bootstrap-cw",
        "bootstrap-ilp",
        "bootstrap-rgs",
        "bootstrap-rng",
        "bootstrap-idp",
        "bootstrap-cr",
        "bootstrap-cgs",
        "bootstrap-pmv",
    ],
}
